# Generated by Django 6.0.5 on 2026-05-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
